version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
    restart: always
    environment:
      DOMAINS: 'splendor.org -> http://web:3000, www.splendor.org -> http://web:3000'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    env_file:
      - .env
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data:
